const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'docs/browser-results'),sizes=[[1920,1080],[1440,900],[1366,768],[1024,768],[768,1024],[390,844],[320,740]],results=[],errors=[];fs.mkdirSync(OUT,{recursive:true});
async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:e.message});throw e;}}
(async()=>{let b;try{b=await chromium.launch({headless:true,...(process.env.SNX_CHROMIUM_PATH?{executablePath:process.env.SNX_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});for(const [width,height]of sizes){const c=await b.newContext({viewport:{width,height},hasTouch:width<800,reducedMotion:'reduce'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>errors.push(r.url()));p.on('popup',()=>errors.push('Unexpected window'));
 async function loaded(){await p.evaluate(async()=>{for(const i of document.images)i.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})))});await p.waitForFunction(()=>!document.querySelector('.phone-frame')||document.querySelector('.phone-frame').style.width);}
 async function screenshot(name){await loaded();const issues=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)}));assert.equal(issues.overflow,false);assert.deepEqual(issues.broken,[]);await p.mouse.move(0,0);await p.screenshot({path:path.join(OUT,`${name}-${width}x${height}.png`),fullPage:!name.startsWith('purchase')});}
 await test(`${width}x${height}: home, one action, loaded portrait/landscape art`,async()=>{await p.goto(process.env.SNX_TEST_URL||pathToFileURL(path.join(ROOT,'index.html')).href);assert.equal(await p.locator('.home-view button').count(),1);await screenshot('home');await p.locator('.enter').focus();await p.keyboard.press('Enter');});
 await test(`${width}x${height}: nine full-image collection cards, no repeated cat`,async()=>{assert.equal(await p.locator('.collection-tile').count(),9);assert.equal(await p.locator('.intro-art').count(),0);await screenshot('collections');assert.ok(await p.locator('.collection-wallpaper').evaluateAll(es=>es.every(e=>getComputedStyle(e).objectFit==='contain')));});
 for(const theme of ['galaxy','inferno','stranger','goldtoon','liquid','quiet','aurora','liquigv2','mousetoon']){
  await test(`${width}x${height} ${theme}: real wallpaper, three categories and scaled phone`,async()=>{await p.locator(`[data-theme="${theme}"]`).click();await screenshot('studio-'+theme);assert.equal(await p.locator('[role="tab"]').count(),3);const rect=await p.locator('.phone').boundingBox();assert.ok(rect.width>130&&rect.width<=301);assert.ok(rect.y>=0&&rect.y+rect.height<=height+1,'Phone stays fully visible');assert.ok((await p.locator('.phone-wallpaper').getAttribute('src')).includes(theme));});
  await test(`${width}x${height} ${theme}: every wallpaper is loadable and applies`,async()=>{const ids=await p.locator('.wallpaper-grid button').evaluateAll(es=>es.map(e=>e.dataset.wallpaper));for(const id of ids){await p.locator(`button[data-wallpaper="${id}"]`).click();await loaded();assert.equal(await p.locator('.phone-screen').getAttribute('data-wallpaper'),id);}await p.reload();await loaded();assert.equal(await p.locator('.phone-screen').getAttribute('data-wallpaper'),ids.at(-1));});
  await test(`${width}x${height} ${theme}: icons apply to selected slot and persist`,async()=>{
   await p.locator('[data-category="icons"]').click();await loaded();assert.ok(await p.locator('.icon-grid button').count()>50);await p.locator('[data-slot="4"]').click();
   const item=p.locator('.icon-grid button').nth(5),src=await item.locator('img').getAttribute('src');await item.click();await loaded();assert.equal(await p.locator('.dialog--icon').count(),1);assert.ok(await p.locator('.icon-detail>img').evaluate(e=>e.naturalWidth>=550));await p.locator('.apply-icon').click();await loaded();assert.equal(await p.locator('[data-slot="4"] img').getAttribute('src'),src);assert.equal(await p.locator('dialog').count(),0);await screenshot('icons-'+theme);
   await p.reload();await loaded();assert.equal(await p.locator('[data-slot="4"] img').getAttribute('src'),src);
  });
  await test(`${width}x${height} ${theme}: widgets apply, retain proportions and remove`,async()=>{await p.locator('[data-category="widgets"]').click();const count=await p.locator('[data-action="widget"]').count();assert.ok(count>0);for(let i=0;i<count;i++){await p.locator('[data-action="widget"]').nth(i).click();await loaded();assert.equal(await p.locator('.phone-widget-asset').count(),1);const wr=await p.locator('.phone-widget-asset').boundingBox(),dr=await p.locator('.phone-dock').boundingBox();assert.ok(wr.y+wr.height<dr.y);if(i===0)await screenshot('widget-'+theme);await p.locator('[data-action="widget"]').nth(i).click();assert.equal(await p.locator('.phone-widget-asset').count(),0);}});
  if(theme==='galaxy'){
   await test(`${width}x${height}: protected images and keyboard tabs`,async()=>{const prevented=await p.locator('.phone-wallpaper').evaluate(el=>['contextmenu','dragstart','auxclick','dblclick'].map(type=>{const e=new Event(type,{bubbles:true,cancelable:true});el.dispatchEvent(e);return e.defaultPrevented}));assert.deepEqual(prevented,[true,true,true,true]);await p.locator('[data-category="widgets"]').focus();await p.keyboard.press('Home');assert.equal(await p.locator('[role="tab"][aria-selected="true"]').getAttribute('data-category'),'wallpapers');await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[role="tab"][aria-selected="true"]').getAttribute('data-category'),'icons');});
   await test(`${width}x${height}: purchase drawer, email, one gift, payment unavailable`,async()=>{await p.locator('.obtain').click();assert.equal(await p.locator('[data-view="studio"]').count(),1);assert.equal(await p.locator('[name="gift-size"]:checked').count(),1);await p.locator('#order-email').fill('contact@example.fr');await p.locator('#order-email').press('ControlOrMeta+A');await p.locator('#order-email').press('Backspace');assert.equal(await p.locator('#order-email').inputValue(),'');await p.locator('#order-email').fill('contact@example.fr');await p.locator('[value="wero"]').check();await p.locator('[name="terms"]').check();assert.ok(await p.locator('.pay-button').isDisabled());await p.getByText('Politique de confidentialité',{exact:true}).click();assert.ok(await p.locator('dialog').evaluate(e=>e.scrollHeight>0));await p.locator('.close-dialog').focus();await p.keyboard.press('Shift+Tab');assert.ok(await p.locator('dialog').evaluate(e=>e.contains(document.activeElement)));if(width<=700){const rect=await p.locator('dialog').boundingBox();assert.ok(Math.abs(rect.width-width)<2);}await p.locator('dialog').evaluate(e=>e.scrollTop=0);await screenshot('purchase');await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.snxPurchase);assert.equal(await p.locator('dialog').count(),0);});
   await test(`${width}x${height}: Back closes drawer and Forward reopens`,async()=>{await p.locator('.obtain').click();await p.goBack();await p.waitForFunction(()=>!document.querySelector('dialog'));assert.equal(await p.locator('.studio-view').count(),1);await p.goForward();await p.locator('dialog').waitFor();await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.snxPurchase);});
  }
  await p.locator('.back-button').click();
 }
 await test(`${width}x${height}: rapid navigation remains stable`,async()=>{await p.evaluate(()=>{for(let i=0;i<30;i++){document.querySelector('[data-theme="galaxy"]').click();document.querySelector('.back-button').click();}document.querySelector('[data-theme="goldtoon"]').click()});await loaded();assert.equal(await p.locator('[data-view]').count(),1);assert.equal(new URL(p.url()).hash,'#studio/goldtoon');});
 await c.close();}
 await test('No console errors, missing resources or unexpected windows',()=>assert.deepEqual(errors,[]));
 }catch(e){console.error(e.message);process.exitCode=1;}finally{const report={type:'Real Chromium interaction and geometry; screenshots separately reviewed',executedAt:new Date().toISOString(),browser:b?await b.version():null,viewports:sizes,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,errors,results};fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed,errors:errors.length}));await b?.close();}})();
