import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath}from'node:url';import {execFileSync}from'node:child_process';import{getThemes,routes}from'../src/data/catalog.js';
const themes=getThemes();
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),results=[];
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);}
function test(name,fn){try{fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:e.message})}}
test('Four canonical screens, thirteen listed theme packs (plus any personal or unlisted themes)',()=>{assert.deepEqual(routes.map(r=>r.id),['home','collections','studio','mine']);assert.deepEqual(themes.filter(t=>!t.custom&&!t.unlisted).map(t=>t.id),['galaxy','inferno','stranger','goldtoon','liquid','quiet','aurora','liquigv2','mousetoon','brume','eclipse','galet','jade']);assert.ok(themes.some(t=>t.id==='elden'&&t.unlisted));});
test('All resources and thumbnails resolve locally',()=>{for(const t of themes){for(const src of [t.cover,...t.wallpapers.flatMap(x=>[x.src,x.thumb]),...t.icons.flatMap(x=>[x.src,x.thumb]),...t.widgets.map(x=>x.src)])assert.ok(fs.statSync(path.join(ROOT,src)).size>0,src);}});
test('Catalog truthful, IDs unique, default icons belong to each theme',()=>{for(const t of themes){assert.ok(t.wallpapers.length&&t.icons.length);for(const w of t.widgets)assert.ok(['static-preview','web-clock'].includes(w.kind));assert.equal(new Set(t.icons.map(i=>i.id)).size,t.icons.length);assert.equal(t.defaultIcons.length,12);for(const id of t.defaultIcons)assert.ok(t.icons.some(i=>i.id===id));for(const i of t.icons)assert.ok(Math.min(i.width,i.height)>=550);}});
test('No source reference screenshot used as interface',()=>{const html=walk(path.join(ROOT,'src')).map(p=>fs.readFileSync(p,'utf8')).join('');assert.ok(!html.includes('2b1dcaf9'));assert.ok(!html.includes('data-action="zoom"'));assert.ok(!html.includes('window.open'));});
test('All HTML and CSS resource links are local and present',()=>{for(const p of [path.join(ROOT,'index.html'),...walk(path.join(ROOT,'styles'))]){const s=fs.readFileSync(p,'utf8');for(const m of s.matchAll(/(?:src|href)="([^"#]+)"|url\(["']?([^"')]+)["']?\)/g)){const v=m[1]||m[2];if(v.startsWith('data:'))continue;assert.ok(!v.startsWith('http'));assert.ok(fs.existsSync(path.resolve(path.dirname(p),v)),v);}}});
test('JavaScript syntax',()=>{for(const p of [...walk(path.join(ROOT,'src')),...walk(path.join(ROOT,'tests')),path.join(ROOT,'app.bundle.js')].filter(p=>/\.(js|mjs|cjs)$/.test(p)))execFileSync(process.execPath,['--check',p]);});
test('Deterministic current bundle',()=>{const before=fs.readFileSync(path.join(ROOT,'app.bundle.js'),'utf8');execFileSync('python',[path.join(ROOT,'scripts/build.py')]);assert.equal(before,fs.readFileSync(path.join(ROOT,'app.bundle.js'),'utf8'));});
const report={type:'Static validation, no visual rendering',executedAt:new Date().toISOString(),passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results};fs.writeFileSync(path.join(ROOT,'docs/static-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.failed)process.exitCode=1;
