const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'..'),bundle=fs.readFileSync(path.join(ROOT,'app.bundle.js'),'utf8'),html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),results=[],errors=[];
function env({hash='',saved=null,storage=true,native=true}={}){const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url:'https://snx.test/'+hash,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window,d=w.document;w.scrollTo=()=>{};if(native){w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')}}if(saved!==null)w.localStorage.setItem('snx.studio.v7',saved);if(!storage)Object.defineProperty(w,'localStorage',{get(){throw new Error('Storage denied')}});w.eval(bundle);return{w,d,close:()=>w.close()};}
function click(d,s){const e=d.querySelector(s);assert.ok(e,s);e.focus();e.click();return e;}
function single(d,v){assert.equal(d.querySelectorAll('[data-view]').length,1);assert.equal(d.querySelector('[data-view]').dataset.view,v);const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);}
function key(w,target,key,more={}){const e=new w.KeyboardEvent('keydown',{key,...more,bubbles:true,cancelable:true});target.dispatchEvent(e);return e;}
const delay=()=>new Promise(r=>setTimeout(r,40));async function test(name,fn){try{await fn();results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:e.message})}}
(async()=>{const e=env(),{w,d}=e;
await test('Home: one Enter button, gradient brand text',()=>{single(d,'home');assert.equal(d.querySelectorAll('.home-view button').length,1);assert.equal(d.querySelector('.home-copy h1 span').textContent,'Studio')});click(d,'.enter');
await test('Collections: nine cards, no repeated cat, no buttons inside cards',()=>{single(d,'collections');assert.equal(d.querySelectorAll('.collection-tile').length,9);assert.equal(d.querySelectorAll('.collection-tile button').length,0);assert.equal(d.querySelectorAll('.intro-art').length,0)});
for(const [theme,count] of [['galaxy',78],['inferno',90],['stranger',72],['goldtoon',79],['liquid',77],['quiet',77],['aurora',53],['liquigv2',58],['mousetoon',78]]){
 await test(theme+': three categories and own assets',()=>{click(d,`[data-theme="${theme}"]`);single(d,'studio');assert.equal(d.querySelectorAll('[role="tab"]').length,3);assert.equal(d.querySelectorAll('.phone-icons button').length,12);assert.ok(d.querySelector('.phone-wallpaper').src.includes(theme));click(d,'[data-category="icons"]');assert.equal(d.querySelectorAll('.icon-grid button').length,count);assert.ok([...d.querySelectorAll('.icon-grid img')].every(i=>i.src.includes(theme)));});
 await test(theme+': enlarge icon then apply to selected phone slot',()=>{click(d,'[data-slot="4"]');const b=d.querySelectorAll('.icon-grid button')[6],source=b.querySelector('img').src;b.click();assert.ok(d.querySelector('.dialog--icon'));click(d,'.apply-icon');assert.equal(d.querySelector('[data-slot="4"] img').src,source);assert.equal(d.querySelectorAll('dialog').length,0);});
 await test(theme+': widget previews apply and remove',()=>{click(d,'[data-category="widgets"]');assert.ok(d.querySelector('[data-action="widget"]'));click(d,'[data-action="widget"]');assert.ok(d.querySelector('.phone-widget-asset'));click(d,'[data-action="widget"]');assert.ok(!d.querySelector('.phone-widget-asset'));});
 await test(theme+': wallpaper changes without new window',()=>{click(d,'[data-category="wallpapers"]');const b=[...d.querySelectorAll('.wallpaper-grid button')].at(-1);b.click();assert.equal(d.querySelector('.phone-screen').dataset.wallpaper,b.dataset.wallpaper);assert.equal(d.querySelectorAll('dialog').length,0)});
 await test(theme+': leaving and returning restores wallpaper and icons',()=>{const wallpaper=d.querySelector('.phone-screen').dataset.wallpaper,icon=d.querySelector('[data-slot="4"] img').src;click(d,'.back-button');assert.equal(d.activeElement.dataset.theme,theme);click(d,`[data-theme="${theme}"]`);assert.equal(d.querySelector('.phone-screen').dataset.wallpaper,wallpaper);assert.equal(d.querySelector('[data-slot="4"] img').src,icon)});
 click(d,'.back-button');
}
click(d,'[data-theme="galaxy"]');
await test('Keyboard tabs use Arrow, Home, End and one tab stop',()=>{const tab=d.querySelector('[data-category="wallpapers"]');key(w,tab,'ArrowRight');assert.equal(d.activeElement.dataset.category,'icons');key(w,d.activeElement,'End');assert.equal(d.activeElement.dataset.category,'widgets');key(w,d.activeElement,'Home');assert.equal(d.activeElement.dataset.category,'wallpapers');assert.equal(d.querySelectorAll('[role="tab"][tabindex="0"]').length,1)});
await test('Context menu, drag, middle click and double click blocked on protected visuals',()=>{const img=d.querySelector('.phone-wallpaper');for(const type of ['contextmenu','dragstart','auxclick','dblclick']){const event=new w.Event(type,{bubbles:true,cancelable:true});img.dispatchEvent(event);assert.equal(event.defaultPrevented,true)}assert.equal(key(w,d.body,'a',{ctrlKey:true}).defaultPrevented,true)});
await test('Purchase drawer remains in Studio and payment cannot be simulated',()=>{click(d,'.obtain');single(d,'studio');assert.equal(w.location.hash,'#studio/galaxy');assert.equal(d.querySelectorAll('dialog').length,1);assert.ok(d.querySelector('.pay-button').disabled);assert.equal(d.querySelectorAll('[name="gift-size"]:checked').length,1);assert.equal(d.querySelectorAll('[name="payment"]').length,2);assert.match(d.querySelector('.pack-content').textContent,/78 icônes/)});
await test('Email editing, Ctrl+A, validation and no email persistence',()=>{const input=d.querySelector('#order-email');input.value='hello@example.fr';assert.ok(input.checkValidity());assert.equal(key(w,input,'a',{ctrlKey:true}).defaultPrevented,false);assert.ok(!w.localStorage.getItem('snx.studio.v7').includes('hello@example.fr'));});
await test('Escape closes purchase and returns focus',async()=>{key(w,d.querySelector('dialog'),'Escape');await delay();assert.equal(d.querySelectorAll('dialog').length,0);single(d,'studio');assert.ok(d.activeElement.classList.contains('obtain'));});
await test('Back and Forward close/reopen purchase within Studio',async()=>{click(d,'.obtain');w.history.back();await delay();single(d,'studio');assert.equal(d.querySelectorAll('dialog').length,0);w.history.forward();await delay();assert.equal(d.querySelectorAll('dialog').length,1);click(d,'.close-dialog');await delay()});
await test('Fifty rapid route cycles keep one view',()=>{for(let i=0;i<50;i++){click(d,'.back-button');click(d,'[data-theme="galaxy"]')}single(d,'studio')});e.close();
for(const [name,o]of [['Denied storage',{storage:false}],['Malformed storage',{saved:'{bad'}],['Invalid selection',{saved:'{"galaxy":{"iconSlots":["invalid"],"wallpaper":"invalid","selectedSlot":999}}'}]])await test(name+' safely falls back',()=>{const e=env({...o,hash:'#studio/galaxy'});assert.equal(e.d.querySelectorAll('.phone-icons img').length,12);click(e.d,'[data-category="icons"]');click(e.d,'.icon-grid button');e.close()});
await test('Non-native dialog fallback',()=>{const e=env({native:false,hash:'#studio/goldtoon'});click(e.d,'.obtain');assert.equal(e.d.querySelector('dialog').getAttribute('aria-modal'),'true');key(e.w,e.d.querySelector('dialog'),'Escape');assert.equal(e.d.querySelectorAll('dialog').length,0);e.close()});
await test('Unknown theme safely canonicalized',()=>{const e=env({hash:'#studio/missing'});assert.equal(e.w.location.hash,'#studio/galaxy');single(e.d,'studio');e.close()});
await test('No DOM runtime errors',()=>assert.deepEqual(errors,[]));const report={type:'jsdom integration, not rendering',executedAt:new Date().toISOString(),passed:results.filter(x=>x.status==='PASS').length,failed:results.filter(x=>x.status==='FAIL').length,results};fs.writeFileSync(path.join(ROOT,'docs/dom-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.failed)process.exitCode=1;
})();
