#!/usr/bin/env python3
"""Deterministic no-dependency bundler for this project's static named ES module imports.
Sources remain standards-based ES modules. Bundle runs directly via file://.
Unsupported syntax causes failure, never a silently partial build.
"""
from pathlib import Path
import re, json, hashlib
ROOT=Path(__file__).resolve().parents[1]
modules={}
def build_module(path):
 path=path.resolve();key=path.relative_to(ROOT).as_posix()
 if key in modules:return key
 text=path.read_text();modules[key]='';exports=[]
 def imp(m):
  target=build_module(path.parent/m.group(2))
  names=re.sub(r'\s+as\s+',': ',m.group(1))
  return f'const {{{names}}} = require({json.dumps(target)});'
 text=re.sub(r'import\s*\{([^}]+)\}\s*from\s*[\'\"]([^\'\"]+)[\'\"];?',imp,text)
 def exp(m):exports.append(m.group(2));return m.group(1)+' '+m.group(2)
 text=re.sub(r'export\s+(const|let|function|class)\s+(\w+)',exp,text)
 if re.search(r'^\s*(import|export)\s',text,re.M):raise ValueError('Unsupported module syntax in '+key)
 modules[key]=text+'\nObject.assign(exports,{'+','.join(exports)+'});'
 return key
entry=build_module(ROOT/'src/main.js')
body='/* Generated by scripts/build.py. Edit src/, not this bundle. */\n(()=>{\n"use strict";\nconst modules={\n'
body+=',\n'.join(json.dumps(key)+':(require,exports)=>{\n'+value+'\n}' for key,value in modules.items())
body+='\n};\nconst cache={};function require(id){if(cache[id])return cache[id];const out={};cache[id]=out;modules[id](require,out);return out;}\nrequire('+json.dumps(entry)+');\n})();\n'
(ROOT/'app.bundle.js').write_text(body)
print(f'Built {len(modules)} modules, {len(body.encode())} bytes, SHA256 {hashlib.sha256(body.encode()).hexdigest()}')
